# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f761daead24a55db83367507d22aa79ea26708a0f9dcbe6053398def665540185a8f52069e7141884404fc52f0f26c63efe769f8ab390c11812e248629fd16a4

test:
  secret_key_base: 95491c9ee4671177c4df906d0588b7d16ec45f97e7fd1c9ee1f3d91677f650eb1ff22e2277a8e314abe6c2632987a99f4c526e368c2b3498b09b72361c4577ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
